name: GitHub City
on:
  workflow_dispatch:
  schedule:
    # Runs every minute
    - cron: "* * * * *"

jobs:
  update-readme:
    name: Update todoist stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: abhisheknaiidu/todoist-readme@master
        with:
            filename: metrics.plugin.skyline.city.svg
            token: NOT_NEEDED
            base: ""
            plugin_skyline: yes
            plugin_skyline_year: 2021
            plugin_skyline_frames: 8
            plugin_skyline_quality: 1
            plugin_skyline_settings: |
                                      {
                                          "url": "https://honzaap.github.io/GithubCity?name=${login}&year=${year}",
                                          "ready": "[...document.querySelectorAll('.display-info span')].map(span => span.innerText).includes('${login}')",
                                          "wait": 4,
                                          "hide": ".github-corner, .footer-link, .buttons-options, .mobile-rotate, .display-info span:first-child"
                                      }
